### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by scaramallion** [pydicom/pyjpegls#9]
And drop it for Python 3.7.

The release workflow will need some updates, too.

@mrbean-bremen do you mind inviting me on pypi so I can setup that side of things?

Also, do you want to review any PRs or are you happy for me to move fast and break things (as the saying goes)?

**Comment by mrbean-bremen** [comment]
Ok, I have renewed the invitation - it had been expired.

**Comment by scaramallion** [comment]
Thanks!
